feat: 🎸 Add google login (not ready)
kacper-cyra/camp-trello-clone pull request #72
Opened 2022-03-21 18:29 UTC by kamack38

2022-04-27 20:00 UTC, kacper-cyra requested changes
Nice 😄

2022-04-27 20:00 UTC, kacper-cyra commented on packages/frontend/src/pages/AuthPage/AuthPage.tsx
> +  // const loginTroughOAuth = () => {
remove

2022-04-28 16:27 UTC, kamack38 commented on packages/backend/src/infrastructure/express/router/task.routes.ts
> +      .get(passport.authenticate('jwt', { session: false }), (req, res) => taskController.findAll(req, res))
How shall I move it?

2022-05-01 21:26 UTC, kacper-cyra commented on packages/backend/src/infrastructure/express/router/task.routes.ts
> +      .get(passport.authenticate('jwt', { session: false }), (req, res) => taskController.findAll(req, res))
Create function - `JwtGuard = () => passport.authenticate('jwt', { session: false })`
and use it as:
`.get(JwtGuard(), (req, res) => ...`

2022-05-01 21:28 UTC, kamack38 commented on packages/backend/src/infrastructure/express/router/task.routes.ts
> +      .get(passport.authenticate('jwt', { session: false }), (req, res) => taskController.findAll(req, res))
Ok

2022-05-07 17:32 UTC, kacper-cyra approved these changes

2022-05-07 17:32 UTC, merged